class TournamentSizeError(Exception):
    pass

class DataError(Exception):
    pass